version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
    networks:
      - nestjs-api
networks:
  nestjs-api:
